### ISSUE TITLE
Not rooted dialog displayed even when device is rooted

### ISSUE THREAD

**Issue by aschereT** [sryze/wirebug#4]
Wirebug checks for /system/bin/su to determine if the device is rooted. but su could be and in fact is placed on other locations on recent SuperSU versions. Ideally it should run 'id' and check output for root.

**Comment by sryze** [comment]
That's a good idea, thanks!  It's now using the output of `su -c id` to determine if root shell is available. It will be released in 0.4.2.

**Comment by aschereT** [comment]
Thanks for fixing this! Love the prompt update!
