### ISSUE TITLE
More informative notification

### ISSUE THREAD

**Issue by karanrajpal14** [sryze/wirebug#5]
The notification can show the IP address to which the user is supposed to connect to. Many a times, I need to reconnect to ADB and I have to open an app for that. 

Also, you can provide a button below the notification that allows the user to disconnect right from it.

**Comment by sryze** [comment]
I agree, this would be useful. Notifications will now include the current IP address and additionally the network name.

A disconnect button seems like a nice idea too, I'll consider adding it as well.

Thanks!
